apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: spark
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ENDPOINT: http://host.docker.internal:9000
  MINIO_BUCKET_LANDING: landing
  MINIO_BUCKET_BRONZE: bronze
  MINIO_BUCKET_SILVER: silver
  MINIO_BUCKET_GOLD: gold
