apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: Postgres-Gold
    type: postgres
    url: postgres:5432
    database: postgres
    user: metabase
    secureJsonData:
      password: metabase
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
